# This file contains all the secrets for the server and client in order to manage and
# secure all of them in the same place. In Kubernetes, this file will be mapped to
# Secrets and all other config files will be mapped to mapConfig

---
# Database Section
oracleDatabasePassword: oracle

#JMS Credentials
jmsSecurityCredentials: devadmin1
